# Generated by Django 5.2.2 on 2025-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='ingredients',
            field=models.TextField(),
        ),
    ]
