# Generated by Django 5.2.2 on 2025-07-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbookapp', '0002_alter_drink_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/videos'),
        ),
    ]
