# Generated by Django 5.2.2 on 2025-07-29 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewbookapp', '0005_liked_delete_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_drinks', to=settings.AUTH_USER_MODEL),
        ),
    ]
